### ISSUE TITLE
HTML Tags werden nicht gefiltert bzw. richtig dargestellt

### ISSUE THREAD

**Issue by theEmil** [CaptainArni/vscode-duden-spell-grammar-check#1]
Hi,

super Erweiterung! Bei mir ist ein Problem aufgetreten: Bei den Hilfevorschlägen werden aktuell die HTML-Tags als reiner Text angezeigt. Ist das gewollt?

![Screenshot 2022-01-21 100822](https://user-images.githubusercontent.com/98152798/150499128-012bfbcb-b43d-4703-b98b-875ffb356505.png)
?

**Comment by CaptainArni** [comment]
Hi,

die HTML Tags gabs noch nicht, als ich die Erweiterung damals geschrieben habe. Ich kann mal bei Gelegenheit schauen, ob ich die darstellen/filtern kann.

**Comment by CaptainArni** [comment]
HTML Tags werden jetzt gefiltert. Update ist draußen.
